---
- name: Watching for Problems on Dynatrace
  hosts: all
  sources:
    - dynatrace.event_driven_ansible.dt_esa_api:
        dt_api_host: "{{ dynatrace_host }}"
        dt_api_token: "{{ dynatrace_token }}"
        delay: "{{ dynatrace_delay }}"

  rules:
    - name: Look for open Process monitor problem
      condition: event.title == "Process unavailable"
      action:
        run_job_template:
          name: Fix Nginx and update all
          organization: "Default"
          job_args:
            extra_vars:
              problemID: "{{ event.displayId }}"
              reporting_host: "{{ event.impactedEntities[0].name }}"
